#%RAML 0.8
---

title: Self Assessment
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Bank Interest
    content: !include docs/bank-interest.md

schemas:
  - Error: !include schemas/Error.json
  - BankInterest: !include schemas/bank/BankInterest.json

/self-assessment:
  /ni/{nino}:
    uriParameters:
      nino:
        displayName: National Insurance Number
        type: string
        required: true
    /bank-interest/{taxYear}:
       displayName: Bank Interest
       uriParameters:
         taxYear:
           displayName: Tax year
           description: Tax year, e.g. 2017-18
           type: string
       get:
         description: Get bank interest
         responses:
           200:
             body:
               application/json:
                 schema: BankInterest
                 example: !include examples/bank/BankInterest.json
       put:
         description: Update bank interest
         body:
           application/json:
             schema: BankInterest
             example: !include examples/bank/BankInterest.json
