#%RAML 0.8
---

title: Self Assessment
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Dividends
    content: !include docs/dividends.md

schemas:
  - Error: !include schemas/Error.json
  - DividendsAnnualSummary: !include schemas/dividends/AnnualSummary.json

/self-assessment:
  /ni/{nino}:
    uriParameters:
      nino:
        displayName: National Insurance Number
        type: string
        required: true
    /dividends/{taxYear}:
     uriParameters:
       taxYear:
         displayName: Tax Year
         type: string
         example: 2016-17
     put:
       description: Update annual summary
       body:
         application/json:
           schema: DividendsAnnualSummary
           example: !include examples/dividends/AnnualSummary.json
       responses:
         204:
         400:
           body:
             application/json:
               schema: Error
               example: !include examples/dividends/errors/AnnualSummary_INVALID_REQUEST.json
     get:
       description: Get annual summary
       responses:
         200:
           body:
             application/json:
               schema: DividendsAnnualSummary
               example: !include examples/dividends/AnnualSummary.json
